name: digitalbeautyhunter
favicon: null
layout_spectrum: 0.2515312936156988
typography_spectrum: 0.2060223186854273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.47096288739703596
  lightness: 0.9556569054257125
  saturation: 0.5903694317676127
  rhythmicContrast: 0.9613115475513041
purpose: []
